### ISSUE TITLE
Create MAN files

### ISSUE THREAD

**Issue by marcelmanz** [CCPablo/js-terminal#4]

**Comment by Leyber91** [comment]
Daily log: 04/12/2020
Issue #4 
Between yesterday night and today morning the manFiles are finished.

By executing the following function at the top of your file:  
let importMan = require('./manFiles/manFileReferenceCaller');

You can call the whole content of man on any place you needed. Example;
Example 1
importMan.manRv (call man content of Rv)
importMan.manPwd (call man content of pwd)
